# Generated by Django 3.0.1 on 2020-04-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, null=True, verbose_name='article name')),
                ('article_txt', models.TextField(max_length=2000, verbose_name='article text')),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('comments', models.IntegerField(default=0, verbose_name='artcle_comments')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('author_name', models.CharField(max_length=100, null=True, verbose_name='article name')),
                ('views', models.BigIntegerField(default=0, verbose_name='views')),
                ('likers', models.TextField(default='', verbose_name='likers')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField(db_index=True, max_length=150)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='author name')),
                ('comment_text', models.CharField(max_length=200, verbose_name='comment text')),
                ('date_pub', models.DateTimeField(verbose_name='comment publication date')),
                ('likes', models.IntegerField(default=0, verbose_name='comment likes')),
                ('likers', models.TextField(default='', verbose_name='comment likers')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='answer text')),
                ('author_name', models.CharField(max_length=50, verbose_name='author name')),
                ('pub_date', models.DateTimeField(verbose_name='answer publication date')),
                ('likes', models.IntegerField(default=0, verbose_name='answer likes')),
                ('likers', models.TextField(default='', verbose_name='answer likers')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Comment')),
            ],
        ),
    ]
